Removed Tests projects since they fail to compile, optional.hpp(40,34): error C2338: static_assert failed
optional.hpp(40,34): error C2338: static_assert failed: 'If you wan t to output boost::optional, include header <boost/optional/optional_io.hpp